### ISSUE TITLE
Mod Version Incompatability

### ISSUE THREAD

**Issue by micle546** [Goldengamer1/Vortex#3]
Server Running 0.36
Client Running: 0.35

```
[14:00:27] [User Authenticator #2/INFO]: UUID of player Xeph69 is 21ad7e96-c050-4802-89f6-59bd5494570c
[14:00:28] [Netty IO #0/INFO] [FML]: Client protocol version 2
[14:00:28] [Netty IO #0/INFO] [FML]: Client attempting to join with 165 mods : ExtraUtilities@1.2.11,iChunUtil@4.2.2,BuildCraft|Robotics@7.0.23,factorization.misc@0.8.98,BiblioCraft@1.10.5,MineFactoryReloaded|CompatRailcraft@1.7.10R2.8.1B1,Translocator@1.1.2.15,MineFactoryReloaded|CompatMystcraft@1.7.10R2.8.1B1,TiCTooltips@1.2.5,extracells@2.2.73,EnderTech@1.7.10-0.3.2.388,ImmersiveEngineering@0.5.4,Doors@4.0.1,WailaHarvestability@1.1.2,libsandstone@1.0.0,Sync@4.0.0,funkylocomotion@1.0,WR-CBE|Core@1.4.1.9,ObsidiPlates@3.0.0.18,factorization.dimensionalSlice@0.8.98,NEIAddons|CraftingTables@1.12.11.36,NEIAddons|ExNihilo@1.12.11.36,spatialio-compat@build-8,ctmlib@1.0.1.5,Forestry@3.6.6.24,FastCraft@1.21,OpenPeripheral@0.4,RedstoneArsenal@1.7.10R1.1.1,ExtraTiC@1.4.5,IronChest@6.0.62.742,CodeChickenCore@1.0.7.47,Natura@2.2.0,Railcraft@9.7.0.0,EE3@0.3.507,appliedenergistics2-core@rv2-stable-10,Botania@r1.7-221,BuildCraft|Compat@7.0.11,NEIAddons@1.12.11.36,ProjRed|Integration@4.7.0pre8.92,BiomesOPlenty@2.1.0,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.1B1,ThaumicTinkerer@unspecified,MineFactoryReloaded@1.7.10R2.8.1B1,journeymap@@JMVERSION@,ae2ee3emcaddon@1.7.10-b5-universal,ThaumicExploration@0.6.0,Morpheus@1.7.10-1.6.10,MineFactoryReloaded|CompatBackTools@1.7.10R2.8.1B1,MineFactoryReloaded|CompatProjRed@1.7.10R2.8.1B1,inventorytweaks@1.59-dev-156-af3bc68,LookingGlass@0.2.0.00,debug@1.0,OpenPeripheralCore@1.2,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.1B1,witchery@0.24.1,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.1B1,FML@7.10.99.99,CompactSolars@4.4.39.315,JABBA@1.2.1,ForgeMultipart@1.2.0.345,MineFactoryReloaded|CompatExtraBiomes@1.7.10R2.8.1B1,Baubles@1.0.1.10,StevesCarts@2.0.0.b18,neiintegration@1.0.12,Mystcraft@0.12.3.00,denseores@1.0,ComputerCraft@1.74,Hats@4.0.1,MineFactoryReloaded|CompatChococraft@1.7.10R2.8.1B1,NEIAddons|Developer@1.12.11.36,ThaumicTinkerer-preloader@0.1,MineFactoryReloaded|CompatTwilightForest@1.7.10R2.8.1B1,Tails@1.7.10-1.4.1a,BuildCraft|Factory@7.0.23,bdlib@1.9.1.97,endercore@1.7.10-0.1.0.23_beta,testdummy@1.0,HatStand@4.0.0,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.1B1,Botany@2.0-pre14,MineFactoryReloaded|CompatForestry@1.7.10R2.8.1B1,BiblioWoodsNatura@1.5,MineFactoryReloaded|CompatSufficientBiomes@1.7.10R2.8.1B1,StorageDrawers@1.7.10-1.5.14,StevesAddons@0.10.16,ForgeMicroblock@1.2.0.345,ProjRed|Exploration@4.7.0pre8.92,BuildCraft|Builders@7.0.23,ThermalFoundation@1.7.10R1.2.0,props@2.0.2,HelpFixer@1.0.7,qmunitylib@1.0,MineFactoryReloaded|CompatForgeMicroblock@1.7.10R2.8.1B1,guideapi@1.7.10-1.0.1-20,factorization.notify@1.0,PneumaticCraft@1.11.7-127,MagicBees@1.7.10-2.3.5,OpenPeripheralIntegration@0.3,BuildCraft|Transport@7.0.23,TwilightForest@2.3.7,mcp@9.05,FinndusFillies@2.1.0.12,NEIAddons|Forestry@1.12.11.36,VillagersNose@1.3a,TMechworks@0.2.14.100,InfiniBows@1.3.0 build 20,Thaumcraft@4.2.3.5,BiblioWoodsBoP@1.9,TConstruct@1.7.10-1.8.7.build979,EnderStorage@1.4.7.36,<CoFH ASM>@000,BinnieCore@2.0-pre14,xreliquary@1.2,MineFactoryReloaded|CompatAtum@1.7.10R2.8.1B1,appliedenergistics2@rv2-stable-10,ProjRed|Transmission@4.7.0pre8.92,menagerie@1.0,MineFactoryReloaded|CompatThermalExpansion@1.7.10R2.8.1B1,BuildCraft|Energy@7.0.23,ThermalDynamics@1.7.10R1.1.0,CarpentersBlocks@3.3.6,Waila@1.5.10,CoFHCore@1.7.10R3.0.4B1,factorization@0.8.98,ProjRed|Core@4.7.0pre8.92,ProjRed|Illumination@4.7.0pre8.92,aobd@2.8.1,StevesFactoryManager@A93,ThermalExpansion@1.7.10R4.0.3B1,OpenBlocks@1.4.4,gendustry@1.5.2.107,BuildCraft|Silicon@7.0.23,MineFactoryReloaded|CompatIC2@1.7.10R2.8.1B1,chisel@2.4.1.40,AWWayofTime@v1.3.3,Morph@0.9.2,ProjRed|Compatibility@4.7.0pre8.92,NEIAddons|AppEng@1.12.11.36,Genetics@2.0-pre14,AgriCraft@1.7.10-1.4.0-beta-2,IC2NuclearControl@2.2.5a-GoingForTheKill,BuildCraft|Core@7.0.23,NEIAddons|Botany@1.12.11.36,NotEnoughItems@1.0.5.111,harvestcraft@1.7.10j,ProjRed|Fabrication@4.7.0pre8.92,IC2@2.2.772-experimental,ExtraBees@2.0-pre14,foxlib@1.7.10-0.7.0,Mantle@1.7.10-0.3.2.jenkins188,OpenMods@0.8,WR-CBE|Addons@1.4.1.9,OpenModsCore@0.8,Forge@10.13.4.1492,ForbiddenMagic@1.7.10-0.57,BigReactors@0.4.3A,vortex@1.7.10-0.36,FlatSigns@2.1.0.19,ExtraTrees@2.0-pre14,EnderIO@1.7.10-2.3.0.413_beta,McMultipart@1.2.0.345,BiblioWoodsForestry@1.7,MrTJPCoreMod@1.1.0.31,MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.1B1,WR-CBE|Logic@1.4.1.9
[14:00:28] [Netty IO #0/INFO] [FML]: Attempting connection with missing mods [ForgeIRC] at CLIENT
[14:00:35] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[14:00:35] [Server thread/ERROR] [FML]: Failed to load extended properties for ExtendedPlayer.  This is a mod issue.
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.goldengamer.vortex.levelHandler.ExtendedPlayer.loadNBTData(ExtendedPlayer.java:75)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.entity.Entity.func_70020_e(Entity.java:1419)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:287)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.management.ServerConfigurationManager.func_72380_a(ServerConfigurationManager.java:263)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:114)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[14:00:35] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[14:00:35] [Server thread/WARN] [Vortexcraft]: Data not found for Xeph69. Trying to load backup data.
[14:00:35] [Server thread/INFO]: Xeph69[/50.173.245.91:50736] logged in with entity id 280489 at (302.89991569533174, 68.0, -151.86569509197517)
[14:00:35] [Server thread/INFO]: Xeph69 joined the game
[14:00:35] [Server thread/INFO] [AgriCraft]: Sending mutations to player: Xeph69
[14:00:35] [Server thread/INFO] [Waila]: Player EntityPlayerMP['Xeph69'/280489, l='world', x=302.90, y=68.00, z=-151.87] connected. Sending ping
[14:00:35] [Server thread/INFO]: [Server] Welcome back, Xeph69
[14:00:35] [Server thread/INFO]: You whisper to Xeph69: Hey there, Xeph69!
[14:00:35] [Server thread/INFO]: You whisper to Xeph69: Welcome to XStream Gaming Network MC#1
```

**Comment by micle546** [comment]
Shouldn't let the client connect with version mismatches: look at changing the Mod ID per version maybe?

I think that's how most mods handle version mismatches. IE: "Connection Refused: Missing Mods ..."

**Comment by micle546** [comment]
Server: 0.36
Client: 0.36

```
[14:12:58] [User Authenticator #3/INFO]: UUID of player Xeph69 is 21ad7e96-c050-4802-89f6-59bd5494570c
[14:12:59] [Netty IO #2/INFO] [FML]: Client protocol version 2
[14:12:59] [Netty IO #2/INFO] [FML]: Client attempting to join with 165 mods : ExtraUtilities@1.2.11,iChunUtil@4.2.2,BuildCraft|Robotics@7.0.23,factorization.misc@0.8.98,BiblioCraft@1.10.5,MineFactoryReloaded|CompatRailcraft@1.7.10R2.8.1B1,Translocator@1.1.2.15,MineFactoryReloaded|CompatMystcraft@1.7.10R2.8.1B1,TiCTooltips@1.2.5,extracells@2.2.73,EnderTech@1.7.10-0.3.2.388,ImmersiveEngineering@0.5.4,Doors@4.0.1,WailaHarvestability@1.1.2,libsandstone@1.0.0,Sync@4.0.0,funkylocomotion@1.0,WR-CBE|Core@1.4.1.9,ObsidiPlates@3.0.0.18,factorization.dimensionalSlice@0.8.98,NEIAddons|CraftingTables@1.12.11.36,NEIAddons|ExNihilo@1.12.11.36,spatialio-compat@build-8,ctmlib@1.0.1.5,Forestry@3.6.6.24,FastCraft@1.21,OpenPeripheral@0.4,RedstoneArsenal@1.7.10R1.1.1,ExtraTiC@1.4.5,IronChest@6.0.62.742,CodeChickenCore@1.0.7.47,Natura@2.2.0,Railcraft@9.7.0.0,EE3@0.3.507,appliedenergistics2-core@rv2-stable-10,Botania@r1.7-221,BuildCraft|Compat@7.0.11,NEIAddons@1.12.11.36,ProjRed|Integration@4.7.0pre8.92,BiomesOPlenty@2.1.0,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.1B1,ThaumicTinkerer@unspecified,MineFactoryReloaded@1.7.10R2.8.1B1,journeymap@@JMVERSION@,ae2ee3emcaddon@1.7.10-b5-universal,ThaumicExploration@0.6.0,Morpheus@1.7.10-1.6.10,MineFactoryReloaded|CompatBackTools@1.7.10R2.8.1B1,MineFactoryReloaded|CompatProjRed@1.7.10R2.8.1B1,inventorytweaks@1.59-dev-156-af3bc68,LookingGlass@0.2.0.00,debug@1.0,OpenPeripheralCore@1.2,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.1B1,witchery@0.24.1,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.1B1,FML@7.10.99.99,CompactSolars@4.4.39.315,JABBA@1.2.1,ForgeMultipart@1.2.0.345,MineFactoryReloaded|CompatExtraBiomes@1.7.10R2.8.1B1,Baubles@1.0.1.10,StevesCarts@2.0.0.b18,neiintegration@1.0.12,Mystcraft@0.12.3.00,denseores@1.0,ComputerCraft@1.74,Hats@4.0.1,MineFactoryReloaded|CompatChococraft@1.7.10R2.8.1B1,NEIAddons|Developer@1.12.11.36,ThaumicTinkerer-preloader@0.1,MineFactoryReloaded|CompatTwilightForest@1.7.10R2.8.1B1,Tails@1.7.10-1.4.1a,BuildCraft|Factory@7.0.23,bdlib@1.9.1.97,endercore@1.7.10-0.1.0.23_beta,testdummy@1.0,HatStand@4.0.0,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.1B1,Botany@2.0-pre14,MineFactoryReloaded|CompatForestry@1.7.10R2.8.1B1,BiblioWoodsNatura@1.5,MineFactoryReloaded|CompatSufficientBiomes@1.7.10R2.8.1B1,StorageDrawers@1.7.10-1.5.14,StevesAddons@0.10.16,ForgeMicroblock@1.2.0.345,ProjRed|Exploration@4.7.0pre8.92,BuildCraft|Builders@7.0.23,ThermalFoundation@1.7.10R1.2.0,props@2.0.2,HelpFixer@1.0.7,qmunitylib@1.0,MineFactoryReloaded|CompatForgeMicroblock@1.7.10R2.8.1B1,guideapi@1.7.10-1.0.1-20,factorization.notify@1.0,PneumaticCraft@1.11.7-127,MagicBees@1.7.10-2.3.5,OpenPeripheralIntegration@0.3,BuildCraft|Transport@7.0.23,TwilightForest@2.3.7,mcp@9.05,FinndusFillies@2.1.0.12,NEIAddons|Forestry@1.12.11.36,VillagersNose@1.3a,TMechworks@0.2.14.100,InfiniBows@1.3.0 build 20,Thaumcraft@4.2.3.5,BiblioWoodsBoP@1.9,TConstruct@1.7.10-1.8.7.build979,EnderStorage@1.4.7.36,<CoFH ASM>@000,BinnieCore@2.0-pre14,xreliquary@1.2,MineFactoryReloaded|CompatAtum@1.7.10R2.8.1B1,appliedenergistics2@rv2-stable-10,ProjRed|Transmission@4.7.0pre8.92,menagerie@1.0,MineFactoryReloaded|CompatThermalExpansion@1.7.10R2.8.1B1,BuildCraft|Energy@7.0.23,ThermalDynamics@1.7.10R1.1.0,CarpentersBlocks@3.3.6,Waila@1.5.10,CoFHCore@1.7.10R3.0.4B1,factorization@0.8.98,ProjRed|Core@4.7.0pre8.92,ProjRed|Illumination@4.7.0pre8.92,aobd@2.8.1,StevesFactoryManager@A93,ThermalExpansion@1.7.10R4.0.3B1,OpenBlocks@1.4.4,gendustry@1.5.2.107,BuildCraft|Silicon@7.0.23,MineFactoryReloaded|CompatIC2@1.7.10R2.8.1B1,chisel@2.4.1.40,AWWayofTime@v1.3.3,Morph@0.9.2,ProjRed|Compatibility@4.7.0pre8.92,NEIAddons|AppEng@1.12.11.36,Genetics@2.0-pre14,AgriCraft@1.7.10-1.4.0-beta-2,IC2NuclearControl@2.2.5a-GoingForTheKill,BuildCraft|Core@7.0.23,NEIAddons|Botany@1.12.11.36,NotEnoughItems@1.0.5.111,harvestcraft@1.7.10j,ProjRed|Fabrication@4.7.0pre8.92,IC2@2.2.772-experimental,ExtraBees@2.0-pre14,foxlib@1.7.10-0.7.0,Mantle@1.7.10-0.3.2.jenkins188,OpenMods@0.8,WR-CBE|Addons@1.4.1.9,OpenModsCore@0.8,Forge@10.13.4.1492,ForbiddenMagic@1.7.10-0.57,BigReactors@0.4.3A,vortex@1.7.10-0.36,FlatSigns@2.1.0.19,ExtraTrees@2.0-pre14,EnderIO@1.7.10-2.3.0.413_beta,McMultipart@1.2.0.345,BiblioWoodsForestry@1.7,MrTJPCoreMod@1.1.0.31,MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.1B1,WR-CBE|Logic@1.4.1.9
[14:12:59] [Netty IO #2/INFO] [FML]: Attempting connection with missing mods [ForgeIRC] at CLIENT
[14:13:03] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[14:13:03] [Server thread/INFO] [Vortexcraft]: [Vortex PROPS] rage from NBT: 0 / 1000
[14:13:03] [Server thread/INFO]: Xeph69[/50.173.245.91:50872] logged in with entity id 595278 at (302.85307374053343, 68.0, -151.94048906578192)
[14:13:03] [Server thread/INFO]: Xeph69 joined the game
[14:13:04] [Server thread/INFO] [AgriCraft]: Sending mutations to player: Xeph69
[14:13:04] [Server thread/INFO] [Waila]: Player EntityPlayerMP['Xeph69'/595278, l='world', x=302.85, y=68.00, z=-151.94] connected. Sending ping
[14:13:04] [Server thread/INFO]: [Server] Welcome back, Xeph69
[14:13:04] [Server thread/INFO]: You whisper to Xeph69: Hey there, Xeph69!
[14:13:04] [Server thread/INFO]: You whisper to Xeph69: Welcome to XStream Gaming Network MC#1

```

**Comment by micle546** [comment]
Fixed as of v.0.37.0
